---
- hosts: all
  vars:
    download_dir: '{{ ansible_env.HOME }}/Downloads'
    software_dir: '{{ ansible_env.HOME }}/opt'
    java_pkg: java-1.8.0-openjdk-devel
    packages: ["emacs", "tmux", "i3", "i3status", "dmenu", "i3lock", "feh", "conky"]
    config_files:
      - { src: "files/i3-config", dest: "~/.config/i3/config" }
      - { src: "files/tmux.conf", dest: "~/.tmux.conf" }
      
  tasks:
  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ download_dir }}"
      - "{{ software_dir }}"
      - "~/.config"
      - "~/.config/i3"

  # It also installs java
  - name: Install sbt
    import_role:
      name: andrewrothstein.scala
    vars:
      sbt_install_parent_dir: "{{ software_dir }}"
    
  - name: Install Intellij
    import_role:
      name: gantsign.intellij
    vars:
       intellij_version: '2017.2.5'
       intellij_edition: 'ultimate'
       intellij_install_dir: '{{ software_dir }}/idea/idea-{{ intellij_edition }}-{{ intellij_version }}'
       intellij_download_dir: '{{ download_dir }}'
       intellij_default_jdk_home: '/usr/local/java'
       intellij_default_maven_home: '{{ software_dir }}/maven'

  - name: Install oh-my-zsh
    import_role:
      name: gantsign.oh-my-zsh
    vars:
      users:
        - username: "{{ ansible_user }}"

  - name: Install packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"
    become: true
    
  - name: Copy config files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      backup: true
    with_items: "{{ config_files }}"
      



    

  


  
